DROP VIEW view_oxarticles_stock;
CREATE VIEW view_oxarticles_stock AS

SELECT b.OXPARENTID AS OXID_VARIANT_GROUP, b.OXID, b.OXPARENTID, a.OXTITLE, a.OXTITLE_1, a.OXTITLE_2, CONCAT(a.OXTITLE,' ', b.OXVARSELECT) AS OXTITLE_COMBINED, CONCAT(a.OXTITLE_1,' ', b.OXVARSELECT_1) AS OXTITLE_1_COMBINED, CONCAT(a.OXTITLE_2,' ', b.OXVARSELECT_2) AS OXTITLE_2_COMBINED, b.OXDELIVERY,
b.OXACTIVE, b.OXPRICE, b.OXBPRICE, b.OXTPRICE, b.OXVARSELECT, b.OXVARSELECT_1, b.OXVARSELECT_2, b.OXSTOCK, b.OXVARSTOCK, b.OXSTOCKFLAG,
COALESCE(NULLIF(b.OXEAN, ''), a.OXEAN) AS OXEAN, COALESCE(NULLIF(b.OXDISTEAN,''), a.OXDISTEAN) AS OXDISTEAN, COALESCE(NULLIF(b.OXMPN, ''), a.OXMPN) AS OXMPN, b.OXARTNUM, COALESCE(NULLIF(b.OXREMINDACTIVE, ''), a.OXREMINDACTIVE) AS OXREMINDACTIVE, COALESCE(NULLIF(b.OXREMINDAMOUNT, ''), a.OXREMINDAMOUNT) AS OXREMINDAMOUNT, b.OXREMINDAMOUNT AS OXREMINDAMOUNT_SELF,
oxmanufacturers.OXTITLE AS manufacturer_OXTITLE, oxmanufacturers.OXTITLE_1 AS manufacturer_OXTITLE_1, oxmanufacturers.OXTITLE_2 AS manufacturer_OXTITLE_2, oxvendor.OXTITLE AS vendor_OXTITLE, oxvendor.OXTITLE_1 AS vendor_OXTITLE_1, oxvendor.OXTITLE_2 AS vendor_OXTITLE_2, b.OXTIMESTAMP, b.OXINSERT,
0 AS NUM_VARIANTS
FROM oxarticles a
LEFT OUTER JOIN oxarticles b ON a.OXID=b.OXPARENTID
LEFT JOIN oxmanufacturers ON COALESCE(NULLIF(b.OXMANUFACTURERID, ''), a.OXMANUFACTURERID) = oxmanufacturers.OXID
LEFT JOIN oxvendor ON COALESCE(NULLIF(b.OXVENDORID, ''), a.OXVENDORID) = oxvendor.OXID
WHERE a.OXPARENTID="" AND b.OXID IS NOT NULL


UNION

SELECT a.OXID AS OXID_VARIANT_GROUP, a.OXID, a.OXPARENTID, a.OXTITLE, a.OXTITLE_1, a.OXTITLE_2, CONCAT(a.OXTITLE,' ', a.OXVARSELECT) AS OXTITLE_COMBINED, CONCAT(a.OXTITLE_1,' ', a.OXVARSELECT_1) AS OXTITLE_1_COMBINED, CONCAT(a.OXTITLE_2,' ', a.OXVARSELECT_2) AS OXTITLE_2_COMBINED, a.OXDELIVERY,
a.OXACTIVE, a.OXPRICE, a.OXBPRICE, a.OXTPRICE,  a.OXVARSELECT, a.OXVARSELECT_1, a.OXVARSELECT_2, a.OXSTOCK, a.OXVARSTOCK, a.OXSTOCKFLAG, a.OXEAN, a.OXDISTEAN, a.OXMPN, a.OXARTNUM, a.OXREMINDACTIVE, a.OXREMINDAMOUNT,a.OXREMINDAMOUNT AS OXREMINDAMOUNT_SELF,
oxmanufacturers.OXTITLE AS manufacturer_OXTITLE, oxmanufacturers.OXTITLE_1 AS manufacturer_OXTITLE_1, oxmanufacturers.OXTITLE_2 AS manufacturer_OXTITLE_2, oxvendor.OXTITLE AS vendor_OXTITLE, oxvendor.OXTITLE_1 AS vendor_OXTITLE_1, oxvendor.OXTITLE_2 AS vendor_OXTITLE_2, a.OXTIMESTAMP, a.OXINSERT,
(SELECT COUNT(*) FROM oxarticles WHERE OXPARENTID=a.OXID) AS NUM_VARIANTS
FROM oxarticles a
LEFT JOIN oxmanufacturers ON a.OXMANUFACTURERID = oxmanufacturers.OXID
LEFT JOIN oxvendor ON a.OXVENDORID = oxvendor.OXID
WHERE OXPARENTID=""
;
